name: GCP TEST

on:
  push:
    branches:
      - feat#41 # 또는 배포하려는 브랜치
    paths:
      - 'Backend/backend_model/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
              docker pull heewoni/cf_model:latest
              docker stop model
              docker rm model
              docker run --env-file .env -d --name model -p 8080:8080 heewoni/cf_model:latest